FROM node:16

RUN apt-get update && apt-get install python3-pip

RUN apt install -y docker.io

RUN sudo systemctl start docker

RUN sudo systemctl start docker

RUN pip install beautifulsoup4

RUN pip install requests

