pipeline {

    agent {
        dockerfile {
            dir 'jenkins'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage("find out"){
            steps{
                echo "find out"
                sh "pwd && ls -lart"
            }
        }
        
    }

    post {
        success {
                script{
                sh "ls -lart"
                sh "chmod 775 ./py/run.sh"
                sh "py/run.sh"
            }
                slackSend channel: '#general', message: 'SUCCESSFUL'
                slackUploadFile 'py/log.html'
        }
        failure {
                script{
                sh "ls -lart"
                sh "chmod 775 ./py/run.sh"
                sh "py/run.sh"
            }
                slackSend channel: '#general', message: 'FAILED-To-DELIVER'
                slackUploadFile 'py/log.html'
        }
    }

    
}
