pipeline {

    agent {
        dockerfile {
            dir 'jenkins'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage("fuck around"){
            steps{
                echo "find out"
                sh "pwd && ls -lart"
            }
        }
        stage ("run command"){
            steps{
                sh "ls -lart"
                sh "chmod 775 ./py/run.sh"
                sh "py/run.sh"
            }
        }
        
    }

    post {
        always {
                slackSend channel: '#general', message: 'Hello Work'
                slackUploadFile 'py/log.html'
        }
    }

    
}
